version: "3"
services:
  krakend:
    image: devopsfaith/krakend:watch
    container_name: krakend
    volumes:
      - ".:/etc/krakend"
    ports:
      - "8080:8080"
    command: [ "run", "-dc", "krakend.json" ]
    networks:
      - my-network

  express-server:
    container_name: express-server
    build:
      context: ./express-server
      dockerfile: Dockerfile
    volumes:
      - ./express-server:/app             
      - ./react-app/build:/app/build      
    ports:
      - "3000:3000"
    networks:
      - my-network

  calendars-service:
    build: ./calendars-service/
    container_name: calendars-service
    env_file: "./calendars-service/.env"
    volumes:
      - ./calendars-service:/app 
    networks:
      - my-network

  meetings-service:
    build: ./meetings-service/
    container_name: meetings-service
    networks:
      - my-network

  participants-service:
    build: ./participants-service/
    container_name: participants-service
    ports:
      - "8080:8080"  # Ensure this line exists
    networks:
      - my-network

  attachments-service:
    build: ./attachments-service/
    container_name: attachments-service
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
